/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAiPerformanceRouteImport } from './routes/dashboard.ai-performance'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminSpecialisteRouteImport } from './routes/dashboard.admin.specialiste'
import { Route as DashboardAdminPermissionsRouteImport } from './routes/dashboard.admin.permissions'
import { Route as DashboardAdminAgentsRouteImport } from './routes/dashboard.admin.agents'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiPerformanceRoute = DashboardAiPerformanceRouteImport.update({
  id: '/ai-performance',
  path: '/ai-performance',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSpecialisteRoute =
  DashboardAdminSpecialisteRouteImport.update({
    id: '/admin/specialiste',
    path: '/admin/specialiste',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPermissionsRoute =
  DashboardAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAgentsRoute = DashboardAdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-performance': typeof DashboardAiPerformanceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/admin/specialiste': typeof DashboardAdminSpecialisteRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-performance': typeof DashboardAiPerformanceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/admin/specialiste': typeof DashboardAdminSpecialisteRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-performance': typeof DashboardAiPerformanceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/admin/specialiste': typeof DashboardAdminSpecialisteRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/confirm'
    | '/dashboard/ai-performance'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/permissions'
    | '/dashboard/admin/specialiste'
    | '/dashboard/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/confirm'
    | '/dashboard/ai-performance'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/permissions'
    | '/dashboard/admin/specialiste'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/confirm'
    | '/dashboard/ai-performance'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/permissions'
    | '/dashboard/admin/specialiste'
    | '/dashboard/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-performance': {
      id: '/dashboard/ai-performance'
      path: '/ai-performance'
      fullPath: '/dashboard/ai-performance'
      preLoaderRoute: typeof DashboardAiPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/specialiste': {
      id: '/dashboard/admin/specialiste'
      path: '/admin/specialiste'
      fullPath: '/dashboard/admin/specialiste'
      preLoaderRoute: typeof DashboardAdminSpecialisteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/permissions': {
      id: '/dashboard/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/dashboard/admin/permissions'
      preLoaderRoute: typeof DashboardAdminPermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/agents': {
      id: '/dashboard/admin/agents'
      path: '/admin/agents'
      fullPath: '/dashboard/admin/agents'
      preLoaderRoute: typeof DashboardAdminAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAiPerformanceRoute: typeof DashboardAiPerformanceRoute
  DashboardAdminAgentsRoute: typeof DashboardAdminAgentsRoute
  DashboardAdminPermissionsRoute: typeof DashboardAdminPermissionsRoute
  DashboardAdminSpecialisteRoute: typeof DashboardAdminSpecialisteRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiPerformanceRoute: DashboardAiPerformanceRoute,
  DashboardAdminAgentsRoute: DashboardAdminAgentsRoute,
  DashboardAdminPermissionsRoute: DashboardAdminPermissionsRoute,
  DashboardAdminSpecialisteRoute: DashboardAdminSpecialisteRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
