/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAiPerformanceRouteImport } from './routes/dashboard.ai-performance'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminSpecialistsRouteImport } from './routes/dashboard.admin.specialists'
import { Route as DashboardAdminAgentsRouteImport } from './routes/dashboard.admin.agents'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiPerformanceRoute = DashboardAiPerformanceRouteImport.update({
  id: '/ai-performance',
  path: '/ai-performance',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSpecialistsRoute =
  DashboardAdminSpecialistsRouteImport.update({
    id: '/admin/specialists',
    path: '/admin/specialists',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAgentsRoute = DashboardAdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-performance': typeof DashboardAiPerformanceRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/specialists': typeof DashboardAdminSpecialistsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-performance': typeof DashboardAiPerformanceRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/specialists': typeof DashboardAdminSpecialistsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-performance': typeof DashboardAiPerformanceRoute
  '/dashboard/admin/agents': typeof DashboardAdminAgentsRoute
  '/dashboard/admin/specialists': typeof DashboardAdminSpecialistsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/confirm'
    | '/dashboard/ai-performance'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/specialists'
    | '/dashboard/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/confirm'
    | '/dashboard/ai-performance'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/specialists'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/confirm'
    | '/dashboard/ai-performance'
    | '/dashboard/admin/agents'
    | '/dashboard/admin/specialists'
    | '/dashboard/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-performance': {
      id: '/dashboard/ai-performance'
      path: '/ai-performance'
      fullPath: '/dashboard/ai-performance'
      preLoaderRoute: typeof DashboardAiPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/specialists': {
      id: '/dashboard/admin/specialists'
      path: '/admin/specialists'
      fullPath: '/dashboard/admin/specialists'
      preLoaderRoute: typeof DashboardAdminSpecialistsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/agents': {
      id: '/dashboard/admin/agents'
      path: '/admin/agents'
      fullPath: '/dashboard/admin/agents'
      preLoaderRoute: typeof DashboardAdminAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAiPerformanceRoute: typeof DashboardAiPerformanceRoute
  DashboardAdminAgentsRoute: typeof DashboardAdminAgentsRoute
  DashboardAdminSpecialistsRoute: typeof DashboardAdminSpecialistsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiPerformanceRoute: DashboardAiPerformanceRoute,
  DashboardAdminAgentsRoute: DashboardAdminAgentsRoute,
  DashboardAdminSpecialistsRoute: DashboardAdminSpecialistsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
